package GUI;

import NapakalakiGame.BadConsequence;

/**
 *
 * @author Diego & Jesus
 */
public class BadConsequenceView extends javax.swing.JPanel {

    private BadConsequence bcModel;

    public void setBC(BadConsequence bc) {
        bcModel = bc;
        
        //BadConsequenceText.setText(bcModel.getText());
        //BadConsequenceText.setEditable(false);
        labelNiveles.setText(Integer.toString(bcModel.getLevels()));
        LabelMuerte.setText(Boolean.toString(bcModel.getDeath()));
        
        if(bcModel.getSpecificVisibleTreasures() != null &&
           bcModel.getSpecificHiddenTreasures() != null){
            visibleTreasures.setText(bcModel.getSpecificVisibleTreasures().toString());
            hiddenTreasures.setText(bcModel.getSpecificHiddenTreasures().toString());
        }
        
        nVisibleTreasures.setText(Integer.toString(bcModel.getNVisibleTreasures()));
        nHiddenTreasures.setText(Integer.toString(bcModel.getNHiddenTreasures()));
        
        repaint();
    }

    public BadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoNiveles = new javax.swing.JLabel();
        labelNiveles = new javax.swing.JLabel();
        TextoMuerte = new javax.swing.JLabel();
        LabelMuerte = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        visibleTreasures = new javax.swing.JLabel();
        hiddenTreasures = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nVisibleTreasures = new javax.swing.JLabel();
        nHiddenTreasures = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Mal rollo pendiente"));

        TextoNiveles.setText("Niveles:");

        labelNiveles.setText("0");

        TextoMuerte.setText("¿Mueres?");

        LabelMuerte.setText("Si/No");

        jLabel2.setText("Visibles");

        jLabel3.setText("Ocultos");

        visibleTreasures.setText("[]");

        hiddenTreasures.setText("[]");

        jLabel4.setText("nVisibles");

        jLabel5.setText("nOcultos");

        nVisibleTreasures.setText("n");

        nHiddenTreasures.setText("n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextoNiveles)
                                .addGap(5, 5, 5)
                                .addComponent(labelNiveles))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextoMuerte)
                                .addGap(5, 5, 5)
                                .addComponent(LabelMuerte))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)
                                .addComponent(nHiddenTreasures))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5)
                                .addComponent(nVisibleTreasures)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNiveles)
                    .addComponent(TextoNiveles, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMuerte)
                    .addComponent(TextoMuerte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nVisibleTreasures))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nHiddenTreasures))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(visibleTreasures))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hiddenTreasures))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMuerte;
    private javax.swing.JLabel TextoMuerte;
    private javax.swing.JLabel TextoNiveles;
    private javax.swing.JLabel hiddenTreasures;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelNiveles;
    private javax.swing.JLabel nHiddenTreasures;
    private javax.swing.JLabel nVisibleTreasures;
    private javax.swing.JLabel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
