package GUI;

import NapakalakiGame.Cultist;
import NapakalakiGame.CultistPlayer;
import NapakalakiGame.Player;
        
import java.awt.Color;
/**
 *
 * @author Diego & Jesus
 */
public class CultistView extends javax.swing.JPanel {

    
    private Cultist cultistModel;
    
    public void setCultist(Player p) {
        
        CultistPlayer cp = null;
        if(p instanceof CultistPlayer){
            cp = (CultistPlayer)p;
        }
        cultistModel = cp.getCultist();
        LabelNombrre1.setText(cultistModel.getName());
        LabelBonus.setText(Integer.toString(cultistModel.getBasicValue()));
        repaint();
    }
    
    public Cultist getCultist(){
        return cultistModel;
    }
    
    public CultistView(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoNombre = new javax.swing.JLabel();
        LabelBonus = new javax.swing.JLabel();
        TextoBonus = new javax.swing.JLabel();
        LabelNombrre1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Sectarios"));

        TextoNombre.setText("Nombre:");

        LabelBonus.setText(" ");

        TextoBonus.setText("Bonificación : ");

        LabelNombrre1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextoBonus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextoNombre)
                        .addGap(1, 1, 1)
                        .addComponent(LabelNombrre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNombre)
                    .addComponent(LabelNombrre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoBonus)
                    .addComponent(LabelBonus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBonus;
    private javax.swing.JLabel LabelNombrre1;
    private javax.swing.JLabel TextoBonus;
    private javax.swing.JLabel TextoNombre;
    // End of variables declaration//GEN-END:variables
}
