package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;
/**
 *
 * @author Diego & Jesus
 */
public class NapakalakiView extends javax.swing.JFrame {
    
    //Modificaciones//
    
    private Napakalaki napakalakiModel;
    
    public void setNapakalaki(Napakalaki n){
    
        napakalakiModel = n;
        monsterView2.setMonster(napakalakiModel.getCurrentMonster());
        playerView2.setPlayer(napakalakiModel.getCurrentPlayer(),napakalakiModel.getNextGUI());
        playerView2.setNapakalaki(napakalakiModel);
        monsterView2.setVisible(false);
       
        //Deshabilitar botones        
        combat.setEnabled(false);
        meet_monster.setEnabled(true);
        next_turn.setEnabled(false);
        repaint();
    }

    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meet_monster = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        next_turn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        combatResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        monsterView2 = new GUI.MonsterView();
        playerView2 = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meet_monster.setText("Mostrar Monstruo");
        meet_monster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meet_monsterActionPerformed(evt);
            }
        });

        combat.setText("Combatir");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        next_turn.setText("Siguiente Turno");
        next_turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_turnActionPerformed(evt);
            }
        });

        jLabel1.setText("Resulado de combate:");

        combatResult.setText("No hay resultado");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel2.setText("Napakalaki : Cultist's Revenge");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(combat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(meet_monster, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(combatResult, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addComponent(next_turn, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(combatResult, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(meet_monster)
                        .addGap(20, 20, 20)
                        .addComponent(combat)
                        .addGap(20, 20, 20)
                        .addComponent(next_turn)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meet_monsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meet_monsterActionPerformed
        //monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        monsterView2.setVisible(true);
        
        //Bloquear botones
        combat.setEnabled(true);
        meet_monster.setEnabled(false);
        next_turn.setEnabled(false);
        
        //Botones de playerview
        playerView2.setMakeVisibleButton(false);
        playerView2.setDiscardButton(false);
        playerView2.setBuyLevelsButton(false);
        
        repaint();
        showView();
    }//GEN-LAST:event_meet_monsterActionPerformed

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        CombatResult cr = napakalakiModel.developCombat();
        combatResult.setText(cr.toString());
        //Bloquear botones
        meet_monster.setEnabled(false);
        combat.setEnabled(false);
        next_turn.setEnabled(true);
        //Botones de playerview
    playerView2.setMakeVisibleButton(true);
        playerView2.setDiscardButton(true);
        playerView2.setBuyLevelsButton(false);
        
        //Actualizar vista de player despues de combatir para hacer visible el BC
        playerView2.setPlayer(napakalakiModel.getCurrentPlayer(),napakalakiModel.getNextGUI());
        repaint();
        showView();
    }//GEN-LAST:event_combatActionPerformed

    private void next_turnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_turnActionPerformed
        if(napakalakiModel.nextTurn()){
	    this.combatResult.setText("");
            this.setNapakalaki(napakalakiModel);
            monsterView2.setVisible(false);
            
            //Bloquear botones
            meet_monster.setEnabled(true);
            combat.setEnabled(false);
            next_turn.setEnabled(false);
            
            //Botones de playerview
            playerView2.setMakeVisibleButton(true);
            playerView2.setDiscardButton(true);
            playerView2.setBuyLevelsButton(true);
            
            showView();
        }   
    }//GEN-LAST:event_next_turnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void  showView(){
        this.setVisible(true);                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private javax.swing.JLabel combatResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton meet_monster;
    private GUI.MonsterView monsterView2;
    private javax.swing.JButton next_turn;
    private GUI.PlayerView playerView2;
    // End of variables declaration//GEN-END:variables
}
